version: 0.1

phases:
  install:
    commands:
      - go get github.com/Masterminds/glide
  pre_build:
    commands:
      - pwd
      - echo $GOPATH

      - glide up
  build:
    commands:
      - make all
artifacts:
  files:
    - testGoBuild
