version: 0.1

phases:
  install:
    commands:
      - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
      - sudo apt-get install glide
      - make prepare 
  build:
    commands:
      - make build
